From Philippe: a patch which upgrades the operator<< for the TArrayX classes. It also add one more test to rootcint to verify that if the '!' has been specified in the linkdef file, both operator<< and operator>> need to be explicitly declared for this class. The error message has been enhanced as follow:
ERROR: In this version of ROOT, the option '!' used in a linkdef file
       implies the actual existence of customized operators.
       The following declaration is now required:
   TBuffer &operator>>(TBuffer &,MyClass *&);
ERROR: In this version of ROOT, the option '!' used in a linkdef file
       implies the actual existence of customized operator.
       The following declaration is now required:
   TBuffer &operator<<(TBuffer &,const MyClass *);
gmake: *** [TeleDict.C] Error 1


git-svn-id: https://root.cern.ch/svn/root/trunk@4721 27541ba8-7e3a-0410-8455-c3a389f83636