From Bertrand: Added -DNOGDI flag in netx/Module.mk, solving compilation error on Windows: netx\src\TXNetSystem.cxx(507) : error C2039: 'SetPortA' : is not a member of 'TUrl'         include\TUrl.h(35) : see declaration of 'TUrl' make: *** [netx/src/TXNetSystem.o] Error 2 Due to the following statement in Winspool.h: #define SetPort SetPortA Adding -DNOGDI in compilation flags avoid to include Winspool.h through Windows.h
git-svn-id: https://root.cern.ch/svn/root/trunk@18201 27541ba8-7e3a-0410-8455-c3a389f83636