Forgot to link against libXrdSys.a which caused: dyld: Symbol not found: __Z10Swap_n2hlly on MacOS X Intel.
git-svn-id: https://root.cern.ch/svn/root/trunk@17368 27541ba8-7e3a-0410-8455-c3a389f83636